url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Devwyre
email: contact@devwyre.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Atiomo S.
  pic: 1
  position: Hr / Design director

- name: Abayomi R.
  pic: 2
  position: Project Director

- name: Nwabuokei E.
  pic: 3
  position: financial Director

- name: Divine E.
  pic: 4
  position: IT Director

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/DevWyre?t=-jPEnPqi7x6LM4dLyphWZw&s=09

  - title: facebook
    url: https://www.facebook.com/share/18XayoBPih/

  - title: instagram
    url: https://www.instagram.com/devwyre?igsh=MWZzd293a3pqejZzdQ==

  - title: github
    url: https://github.com/DevWyre

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty